import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faTwitter,
  faMedium,
  faGithub,
  faDiscourse,
  faCcVisa,
  faCcMastercard,
  faCcJcb,
  faCcDiscover,
  faCcDinersClub,
  faCcAmex,
  faEthereum,
} from '@fortawesome/free-brands-svg-icons';
import {
  faAngleDown as farAngleDown,
  faAngleLeft as farAngleLeft,
  faAngleRight as farAngleRight,
  faArrowDown as farArrowDown,
  faArrowUp as farArrowUp,
  faBars as farBars,
  faCheck as farCheck,
  faTimes as farTimes,
} from '@fortawesome/pro-regular-svg-icons';
import {
  faAnalytics as falAnalytics,
  faArchive as falArchive,
  faArrowRight as falArrowRight,
  faBadgeCheck as falBadgeCheck,
  faBooks as falBooks,
  faBroadcastTower as falBroadcastTower,
  faCalendarAlt as falCalendarAlt,
  faClipboard as falClipboard,
  faClock as falClock,
  faChartBar as falChartBar,
  faChartLine as falChartLine,
  faCheckCircle as falCheckCircle,
  faCode as falCode,
  faCogs as falCogs,
  faColumns as falColumns,
  faComment as falComment,
  faComments as falComments,
  faCreditCardBlank as falCreditCardBlank,
  faDatabase as falDatabase,
  faEllipsisH as falEllipsisH,
  faEnvelope as falEnvelope,
  faExclamationCircle as falExclamationCircle,
  faExclamationTriangle as falExclamationTriangle,
  faFileAlt as falFileAlt,
  faFileInvoice as falFileInvoice,
  faFilePdf as falFilePdf,
  faFileSignature as falFileSignature,
  faFrown as falFrown,
  faHeartbeat as falHeartbeat,
  faHexagon as falHexagon,
  faInfoCircle as falInfoCircle,
  faLock as falLock,
  faMagic as falMagic,
  faMoonStars as falMoonStars,
  faMinusHexagon as falMinusHexagon,
  faNetworkWired as falNetworkWired,
  faPencil as falPencil,
  faPlus as falPlus,
  faPlusHexagon as falPlusHexagon,
  faProjectDiagram as falProjectDiagram,
  faQuestionCircle as falQuestionCircle,
  faQuestion as falQuestion,
  faRabbitFast as falRabbitFast,
  faRedo as falRedo,
  faRocket as falRocket,
  faSlash as falSlash,
  faSlidersV as falSlidersV,
  faTachometer as falTachometer,
  faTicketAlt as falTicketAlt,
  faTimesCircle as falTimesCircle,
  faThumbsUp as falThumbsUp,
  faTrophyAlt as falTrophyAlt,
  faUser as falUser,
  faUsers as falUsers,
  faUserMinus as falUserMinus,
  faWrench as falWrench,
  faCog as falCog,
  faSignOut as falSignOut,
} from '@fortawesome/pro-light-svg-icons';
import { faCheckCircle, faChevronDown, faCreditCard, faTimesCircle } from '@fortawesome/pro-solid-svg-icons';

library.add(
  faTwitter,
  faMedium,
  faGithub,
  faDiscourse,
  faCcVisa,
  faCcMastercard,
  faCcJcb,
  faCcDiscover,
  faCcDinersClub,
  faCcAmex,
  faEthereum,
  farAngleDown,
  farAngleLeft,
  farAngleRight,
  farArrowUp,
  farArrowDown,
  farBars,
  farCheck,
  farTimes,
  falAnalytics,
  falArchive,
  falArrowRight,
  falBadgeCheck,
  falBooks,
  falBroadcastTower,
  falCalendarAlt,
  falChartBar,
  falChartLine,
  falCheckCircle,
  falClipboard,
  falClock,
  falCode,
  falCogs,
  falColumns,
  falComment,
  falComments,
  falCreditCardBlank,
  falDatabase,
  falEllipsisH,
  falEnvelope,
  falExclamationCircle,
  falExclamationTriangle,
  falFileAlt,
  falFileInvoice,
  falFilePdf,
  falFileSignature,
  falFrown,
  falHeartbeat,
  falHexagon,
  falInfoCircle,
  falLock,
  falMagic,
  falMoonStars,
  falMinusHexagon,
  falNetworkWired,
  falPencil,
  falPlus,
  falPlusHexagon,
  falProjectDiagram,
  falQuestion,
  falQuestionCircle,
  falRabbitFast,
  falRedo,
  falRocket,
  falSlash,
  falSlidersV,
  falTachometer,
  falThumbsUp,
  falTicketAlt,
  falTimesCircle,
  falTrophyAlt,
  falUser,
  falUsers,
  falUserMinus,
  falWrench,
  falCog,
  falSignOut,
  faCheckCircle,
  faChevronDown,
  faCreditCard,
  faTimesCircle,
);
